server:
  port: 80
  servlet:
    context-path: /
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/





      
      
      
